package theme

import (
	"fmt"
	"github.com/prettyletto/omagen/backend/internal/fsutil"
	"path/filepath"
	"strings"
)

// WriteHyprland preserves the existing window-level theme output. Shell
// extras are deliberately written separately by WriteShell.
func WriteHyprland(themeDir string, p Palette, borderStyle, shape, spacing, depth string) error {
	if !validChoice(borderStyle, "solid", "split", "split_top", "split_bottom", "blend", "neon") || !validChoice(shape, "native", "soft", "rounded") || !validChoice(spacing, "native", "compact", "airy") || !validChoice(depth, "native", "flat", "shadow") {
		return fmt.Errorf("invalid desktop style")
	}
	accent, fg := hyprColor(p.Accent), hyprColor(p.Foreground)
	active := fmt.Sprintf("%q", accent)
	switch borderStyle {
	case "split", "split_top":
		active = gradientLua(accent, fg, 90)
	case "split_bottom":
		active = gradientLua(fg, accent, 90)
	case "blend":
		active = gradientLua(accent, hyprColor(p.Blue), 135)
	case "neon":
		active = gradientLua(accent, hyprColor(p.Magenta), 45)
	}
	var b strings.Builder
	fmt.Fprintf(&b, "-- Generated by Omagen. Window style: border=%s shape=%s spacing=%s depth=%s.\nlocal active_border_color = %s\nlocal inactive_border_color = %q\n\nhl.config({\n  general = {\n    col = { active_border = active_border_color, inactive_border = inactive_border_color },\n", borderStyle, shape, spacing, depth, active, hyprColor(p.DarkForeground))
	if spacing == "compact" {
		b.WriteString("    gaps_in = 4, gaps_out = 5,\n")
	}
	if spacing == "airy" {
		b.WriteString("    gaps_in = 8, gaps_out = 14,\n")
	}
	b.WriteString("  },\n  group = { col = { border_active = active_border_color, border_inactive = inactive_border_color }, },\n")
	if shape != "native" || depth != "native" {
		b.WriteString("  decoration = {\n")
		if shape == "soft" {
			b.WriteString("    rounding = 3, rounding_power = 3,\n")
		}
		if shape == "rounded" {
			b.WriteString("    rounding = 8, rounding_power = 3,\n")
		}
		if depth == "flat" {
			b.WriteString("    shadow = { enabled = false },\n")
		}
		if depth == "shadow" {
			fmt.Fprintf(&b, "    shadow = { enabled = true, render_power = 4, range = 16, color = %q },\n", hyprRGBA(p.DarkerBackground, "b3"))
		}
		b.WriteString("  },\n")
	}
	b.WriteString("})\n")
	return fsutil.AtomicWriteFile(filepath.Join(themeDir, "hyprland.lua"), []byte(b.String()), 0644)
}

func gradientLua(first, second string, angle int) string {
	return fmt.Sprintf("{ colors = { %q, %q }, angle = %d }", first, second, angle)
}
func hyprColor(hex string) string {
	if len(hex) == 7 {
		return "rgb(" + hex[1:] + ")"
	}
	return "rgb(ffffff)"
}
func hyprRGBA(hex, alpha string) string {
	if len(hex) == 7 {
		return fmt.Sprintf("rgba(%s%s)", hex[1:], alpha)
	}
	return "rgba(ffffff" + alpha + ")"
}
