package theme

import (
	"fmt"
	"github.com/prettyletto/omagen/backend/internal/fsutil"
	"path/filepath"
	"strings"
)

// WriteHyprland preserves the existing window-level theme output. Shell
// extras are deliberately written separately by WriteShell.
func WriteHyprland(themeDir string, p Palette, borderStyle string, borderSize int, shape, spacing, depth, inactive string) error {
	if !validChoice(borderStyle, "solid", "split", "split_top", "split_bottom", "blend", "neon", "spin") || borderSize < 0 || borderSize > 10 || !validChoice(shape, "native", "soft", "rounded") || !validChoice(spacing, "native", "compact", "airy") || !validChoice(depth, "native", "flat", "shadow") || !validChoice(inactive, "native", "shadow", "blur") {
		return fmt.Errorf("invalid desktop style")
	}
	accent, fg := hyprColor(p.Accent), hyprColor(p.Foreground)
	active := fmt.Sprintf("%q", accent)
	switch borderStyle {
	case "split", "split_top":
		active = gradientLua(accent, fg, 90)
	case "split_bottom":
		active = gradientLua(fg, accent, 90)
	case "blend":
		active = gradientLua(accent, hyprColor(p.Blue), 135)
	case "neon":
		active = gradientLua(accent, hyprColor(p.Magenta), 0)
	case "spin":
		// A two-stop accent/blue gradient can be nearly monochromatic in
		// extracted palettes. Add a contrasting magenta stop and repeat the
		// accent so the loop has an obvious moving seam.
		active = gradientLuaColors(0, accent, hyprColor(p.Blue), hyprColor(p.Magenta), accent)
	}
	var b strings.Builder
	fmt.Fprintf(&b, "-- Generated by Omagen. Window style: border=%s border_size=%d shape=%s spacing=%s depth=%s inactive=%s.\nlocal active_border_color = %s\nlocal inactive_border_color = %q\n", borderStyle, borderSize, shape, spacing, depth, inactive, active, hyprColor(p.DarkForeground))
	if borderStyle == "neon" {
		fmt.Fprintf(&b, "local active_shadow_color = %q\nlocal inactive_shadow_color = %q\nlocal active_glow_color = %q\nlocal inactive_glow_color = %q\n", hyprRGBA(p.Accent, "d0"), hyprRGBA(p.DarkForeground, "55"), hyprRGBA(p.Accent, "d0"), hyprRGBA(p.DarkForeground, "35"))
	}
	b.WriteString("\nhl.config({\n  general = {\n    col = { active_border = active_border_color, inactive_border = inactive_border_color },\n")
	if borderSize > 0 {
		fmt.Fprintf(&b, "    border_size = %d,\n", borderSize)
	}
	if spacing == "compact" {
		b.WriteString("    gaps_in = 4, gaps_out = 5,\n")
	}
	if spacing == "airy" {
		b.WriteString("    gaps_in = 8, gaps_out = 14,\n")
	}
	b.WriteString("  },\n  group = { col = { border_active = active_border_color, border_inactive = inactive_border_color }, },\n")
	if shape != "native" || depth != "native" || borderStyle == "neon" || inactive != "native" {
		b.WriteString("  decoration = {\n")
		if shape == "soft" {
			b.WriteString("    rounding = 3, rounding_power = 3,\n")
		}
		if shape == "rounded" {
			b.WriteString("    rounding = 8, rounding_power = 3,\n")
		}
		shadowEnabled := depth == "shadow" || borderStyle == "neon" || inactive == "shadow"
		if depth == "flat" && !shadowEnabled {
			b.WriteString("    shadow = { enabled = false },\n")
		}
		if shadowEnabled {
			activeShadow := fmt.Sprintf("%q", hyprRGBA(p.DarkerBackground, "e6"))
			inactiveShadow := fmt.Sprintf("%q", hyprRGBA(p.DarkerBackground, "b8"))
			if borderStyle == "neon" {
				activeShadow = "active_shadow_color"
				inactiveShadow = "inactive_shadow_color"
			}
			if inactive == "shadow" && borderStyle != "neon" {
				inactiveShadow = fmt.Sprintf("%q", hyprRGBA(p.DarkerBackground, "d0"))
			}
			rangePx := 18
			if borderStyle == "neon" {
				rangePx = 24
			}
			fmt.Fprintf(&b, "    shadow = { enabled = true, render_power = 3, range = %d, color = %s, color_inactive = %s },\n", rangePx, activeShadow, inactiveShadow)
		}
		if borderStyle == "neon" {
			b.WriteString("    glow = { enabled = true, range = 16, render_power = 3, color = active_glow_color, color_inactive = inactive_glow_color },\n")
		}
		if inactive == "shadow" {
			b.WriteString("    dim_inactive = true, dim_strength = 0.32,\n")
		}
		if inactive == "blur" {
			// Hyprland blurs the background behind translucent windows; it does
			// not blur the pixels rendered by an opaque application. Pair that
			// with inactive opacity and dimming so the pane recedes reliably.
			b.WriteString("    inactive_opacity = 0.58, dim_inactive = true, dim_strength = 0.62,\n")
			b.WriteString("    blur = { enabled = true, size = 16, passes = 3, ignore_opacity = false, new_optimizations = true },\n")
		}
		b.WriteString("  },\n")
	}
	b.WriteString("})\n")
	if borderStyle == "spin" || borderStyle == "neon" {
		b.WriteString("\n-- Keep the accent gradient moving around the focused pane.\n")
		// Hyprland measures animation speed in deciseconds (1 = 100 ms).
		// Values below 1 make the gradient complete a cycle almost
		// instantaneously, which looks static instead of visibly moving.
		speed := "36"
		if borderStyle == "neon" {
			speed = "30"
		}
		fmt.Fprintf(&b, "hl.animation({ leaf = \"borderangle\", enabled = true, speed = %s, bezier = \"linear\", style = \"loop\" })\n", speed)
	}
	return fsutil.AtomicWriteFile(filepath.Join(themeDir, "hyprland.lua"), []byte(b.String()), 0644)
}

func gradientLua(first, second string, angle int) string {
	return fmt.Sprintf("{ colors = { %q, %q }, angle = %d }", first, second, angle)
}

func gradientLuaColors(angle int, colors ...string) string {
	quoted := make([]string, len(colors))
	for i, color := range colors {
		quoted[i] = fmt.Sprintf("%q", color)
	}
	return fmt.Sprintf("{ colors = { %s }, angle = %d }", strings.Join(quoted, ", "), angle)
}
func hyprColor(hex string) string {
	if len(hex) == 7 {
		return "rgb(" + hex[1:] + ")"
	}
	return "rgb(ffffff)"
}
func hyprRGBA(hex, alpha string) string {
	if len(hex) == 7 {
		return fmt.Sprintf("rgba(%s%s)", hex[1:], alpha)
	}
	return "rgba(ffffff" + alpha + ")"
}
