package theme

import (
	"fmt"
	"github.com/prettyletto/omagen/backend/internal/fsutil"
	"github.com/prettyletto/omagen/backend/internal/session"
	"path/filepath"
	"strings"
)

// WriteHyprland preserves the existing window-level theme output. Shell
// extras are deliberately written separately by WriteShell.
func WriteHyprland(themeDir string, p Palette, borderStyle string, borderSize int, shape, spacing, depth, inactive string, borderSpeed ...int) error {
	animations := session.DefaultAnimationsStyle()
	if len(borderSpeed) > 0 && borderSpeed[0] != 0 {
		animations.BorderSpeed = borderSpeed[0]
	}
	return WriteHyprlandWithAnimations(themeDir, p, borderStyle, borderSize, shape, spacing, depth, "native", inactive, animations.BorderSpeed, animations)
}

func WriteHyprlandWithAnimations(themeDir string, p Palette, borderStyle string, borderSize int, shape, spacing, depth, active, inactive string, borderSpeed int, animations session.AnimationsStyle) error {
	animations = session.NormalizeAnimationsStyle(animations)
	spinSpeed := 36
	if borderSpeed != 0 {
		spinSpeed = borderSpeed
	} else if animations.BorderSpeed != 0 {
		spinSpeed = animations.BorderSpeed
	}
	if inactive == "shadow_full" {
		inactive = "shadow_only"
	}
	if !validChoice(borderStyle, "solid", "split", "split_top", "split_bottom", "blend", "neon", "spin") || borderSize < -1 || borderSize > 24 || spinSpeed < 10 || spinSpeed > 100 || !validChoice(shape, "native", "subtle", "soft", "rounded", "pill") || !validChoice(spacing, "native", "compact", "airy") || !validChoice(depth, "native", "flat", "shadow") || !validChoice(active, "native", "frosted_light", "frosted_balanced", "frosted_rich", "blur") || !validChoice(inactive, "native", "shadow", "shadow_only", "blur", "frosted_light", "frosted_balanced", "frosted_rich") {
		return fmt.Errorf("invalid desktop style")
	}
	if active == "blur" {
		active = "frosted_balanced"
	}
	if inactive == "blur" {
		inactive = "frosted_balanced"
	}
	activeFrosted, activeProfile := frostedBackdropProfile(active)
	inactiveFrosted, inactiveProfile := frostedBackdropProfile(inactive)
	accent, fg := hyprColor(p.Accent), hyprColor(p.Foreground)
	activeBorder := fmt.Sprintf("%q", accent)
	switch borderStyle {
	case "split", "split_top":
		activeBorder = gradientLua(accent, fg, 90)
	case "split_bottom":
		activeBorder = gradientLua(fg, accent, 90)
	case "blend":
		activeBorder = gradientLua(accent, hyprColor(p.Blue), 135)
	case "neon":
		activeBorder = gradientLua(accent, hyprColor(p.Magenta), 0)
	case "spin":
		// A two-stop accent/blue gradient can be nearly monochromatic in
		// extracted palettes. Add a contrasting magenta stop and repeat the
		// accent so the loop has an obvious moving seam.
		activeBorder = gradientLuaColors(0, accent, hyprColor(p.Blue), hyprColor(p.Magenta), accent)
	}
	var b strings.Builder
	fmt.Fprintf(&b, "-- Generated by Omagen. Window style: border=%s border_size=%d shape=%s spacing=%s depth=%s active=%s inactive=%s.\nlocal active_border_color = %s\nlocal inactive_border_color = %q\n", borderStyle, borderSize, shape, spacing, depth, active, inactive, activeBorder, hyprColor(p.DarkForeground))
	b.WriteString("if _omagen_border_angle_timer then _omagen_border_angle_timer:set_enabled(false) end\n")
	if borderStyle == "neon" {
		fmt.Fprintf(&b, "local active_shadow_color = %q\nlocal inactive_shadow_color = %q\nlocal active_glow_color = %q\nlocal inactive_glow_color = %q\n", hyprRGBA(p.Accent, "d0"), hyprRGBA(p.DarkForeground, "55"), hyprRGBA(p.Accent, "d0"), hyprRGBA(p.DarkForeground, "35"))
	}
	b.WriteString("\nhl.config({\n  general = {\n    col = { active_border = active_border_color, inactive_border = inactive_border_color },\n")
	if borderSize >= 0 {
		fmt.Fprintf(&b, "    border_size = %d,\n", borderSize)
	}
	if spacing == "compact" {
		b.WriteString("    gaps_in = 4, gaps_out = 5,\n")
	}
	if spacing == "airy" {
		b.WriteString("    gaps_in = 8, gaps_out = 14,\n")
	}
	b.WriteString("  },\n  group = { col = { border_active = active_border_color, border_inactive = inactive_border_color }, },\n")
	if shape != "native" || depth != "native" || borderStyle == "neon" || active != "native" || inactive != "native" {
		b.WriteString("  decoration = {\n")
		switch shape {
		case "subtle":
			b.WriteString("    rounding = 2, rounding_power = 3,\n")
		case "soft":
			b.WriteString("    rounding = 4, rounding_power = 3,\n")
		case "rounded":
			b.WriteString("    rounding = 8, rounding_power = 3,\n")
		case "pill":
			b.WriteString("    rounding = 16, rounding_power = 3,\n")
		}
		shadowEnabled := depth == "shadow" || borderStyle == "neon" || inactive == "shadow" || inactive == "shadow_only"
		if depth == "flat" && !shadowEnabled {
			b.WriteString("    shadow = { enabled = false },\n")
		}
		if shadowEnabled {
			activeShadow := fmt.Sprintf("%q", hyprRGBA(p.DarkerBackground, "e6"))
			inactiveShadow := fmt.Sprintf("%q", hyprRGBA(p.DarkerBackground, "b8"))
			if borderStyle == "neon" {
				activeShadow = "active_shadow_color"
				inactiveShadow = "inactive_shadow_color"
			}
			if inactive == "shadow" && borderStyle != "neon" {
				inactiveShadow = fmt.Sprintf("%q", hyprRGBA(p.DarkerBackground, "d0"))
			}
			if inactive == "shadow_only" && borderStyle != "neon" {
				// Keep this shadow visibly transparent so the active Omarchy and
				// application opacity policy remains visible underneath it.
				inactiveShadow = fmt.Sprintf("%q", hyprRGBA(p.DarkerBackground, "88"))
			}
			rangePx := 18
			if borderStyle == "neon" {
				rangePx = 24
			}
			fmt.Fprintf(&b, "    shadow = { enabled = true, render_power = 3, range = %d, color = %s, color_inactive = %s },\n", rangePx, activeShadow, inactiveShadow)
		}
		if borderStyle == "neon" {
			b.WriteString("    glow = { enabled = true, range = 16, render_power = 3, color = active_glow_color, color_inactive = inactive_glow_color },\n")
		}
		if inactive == "shadow" {
			b.WriteString("    dim_inactive = true, dim_strength = 0.32,\n")
		}
		if activeFrosted || inactiveFrosted {
			// This is compositor background blur through the translucent inactive
			// surface. It cannot blur opaque client pixels such as application text.
			if inactiveFrosted {
				// Blur profiles inherit the user's existing opacity policy. The
				// profile only contributes optional dim strength and blur quality.
				fmt.Fprintf(&b, "    dim_inactive = true, dim_strength = %.2f,\n", inactiveProfile.dim)
			}
			profile := activeProfile
			if !activeFrosted || (inactiveFrosted && inactiveProfile.size > profile.size) {
				profile = inactiveProfile
			}
			// Keep inactive opacity as part of the frosted look without letting it
			// suppress the backdrop sample. Otherwise opaque client themes are
			// merely dimmed and the result reads as a shadow instead of glass blur.
			fmt.Fprintf(&b, "    blur = { enabled = true, size = %d, passes = %d, ignore_opacity = true, new_optimizations = true },\n", profile.size, profile.passes)
		}
		b.WriteString("  },\n")
	}
	b.WriteString("})\n")
	if activeFrosted || inactiveFrosted {
		// Live Canvas is a Quickshell layer surface, not a managed window. The
		// window decoration blur above cannot affect it, so scope a layer rule
		// to the panel's namespace as well. The panel itself remains translucent
		// in QML so Hyprland can sample and blur the backdrop behind it.
		b.WriteString("\n-- Blur the translucent Omagen Live Canvas layer surface.\n")
		b.WriteString("hl.layer_rule({ name = \"omagen-live-canvas-backdrop-blur\", match = { namespace = \"^omagen-live-canvas$\" }, blur = true, blur_popups = true, ignore_alpha = 0.20 })\n")
	}
	if animations.Window != "native" || animations.Workspace != "native" || animations.ReducedMotion {
		writeAnimationSettings(&b, animations)
	}
	if (borderStyle == "spin" || borderStyle == "neon") && animations.Border != "static" && !animations.ReducedMotion {
		b.WriteString("\n-- Keep the accent gradient moving around the focused pane.\n")
		// Hyprland measures animation speed in deciseconds (1 = 100 ms).
		// The timer below also updates the angle so a theme switch can start
		// spinning existing windows whose border callback was created while
		// borderangle was disabled.
		speed := spinSpeed
		if borderStyle == "neon" {
			speed = 30
		}
		fmt.Fprintf(&b, "hl.animation({ leaf = \"borderangle\", enabled = true, speed = %d, bezier = \"linear\", style = \"loop\" })\n", speed)
		b.WriteString("local _omagen_border_angle = 0\n")
		fmt.Fprintf(&b, "_omagen_border_angle_timer = hl.timer(function()\n  _omagen_border_angle = (_omagen_border_angle + %0.4f) %% 360\n  hl.config({ general = { col = { active_border = { colors = active_border_color.colors, angle = _omagen_border_angle } } } })\nend, { timeout = 100, type = \"repeat\" })\n", 360.0/float64(speed))
	}
	return fsutil.AtomicWriteFile(filepath.Join(themeDir, "hyprland.lua"), []byte(b.String()), 0644)
}

func writeAnimationSettings(b *strings.Builder, animations session.AnimationsStyle) {
	if animations.ReducedMotion || animations.Window == "none" {
		b.WriteString("hl.animation({ leaf = \"windows\", enabled = false })\n")
		b.WriteString("hl.animation({ leaf = \"windowsIn\", enabled = false })\n")
		b.WriteString("hl.animation({ leaf = \"windowsOut\", enabled = false })\n")
	} else {
		speed, bezier := "3.79", "easeOutQuint"
		if animations.Window == "snappy" {
			speed, bezier = "5.5", "quick"
		}
		fmt.Fprintf(b, "hl.animation({ leaf = \"windows\", enabled = true, speed = %s, bezier = %q })\n", speed, bezier)
		fmt.Fprintf(b, "hl.animation({ leaf = \"windowsIn\", enabled = true, speed = %s, bezier = %q, style = \"popin 87%%\" })\n", speed, bezier)
		fmt.Fprintf(b, "hl.animation({ leaf = \"windowsOut\", enabled = true, speed = %s, bezier = \"linear\", style = \"popin 87%%\" })\n", speed)
	}
	if animations.ReducedMotion || animations.Workspace == "none" {
		b.WriteString("hl.animation({ leaf = \"workspaces\", enabled = false })\n")
	} else if animations.Workspace == "snappy" {
		b.WriteString("hl.animation({ leaf = \"workspaces\", enabled = true, speed = 5, bezier = \"quick\", style = \"slide\" })\n")
	} else {
		b.WriteString("hl.animation({ leaf = \"workspaces\", enabled = true, speed = 3, bezier = \"easeOutQuint\", style = \"slide\" })\n")
	}
}

type frostedProfile struct {
	dim    float64
	size   int
	passes int
}

func frostedBackdropProfile(inactive string) (bool, frostedProfile) {
	switch inactive {
	case "blur", "frosted_balanced":
		// Balanced favours a visible backdrop over the old shadow-heavy dim.
		return true, frostedProfile{dim: 0.26, size: 18, passes: 3}
	case "frosted_light":
		return true, frostedProfile{dim: 0.12, size: 10, passes: 2}
	case "frosted_rich":
		return true, frostedProfile{dim: 0.34, size: 24, passes: 4}
	default:
		return false, frostedProfile{}
	}
}

func gradientLua(first, second string, angle int) string {
	return fmt.Sprintf("{ colors = { %q, %q }, angle = %d }", first, second, angle)
}

func gradientLuaColors(angle int, colors ...string) string {
	quoted := make([]string, len(colors))
	for i, color := range colors {
		quoted[i] = fmt.Sprintf("%q", color)
	}
	return fmt.Sprintf("{ colors = { %s }, angle = %d }", strings.Join(quoted, ", "), angle)
}
func hyprColor(hex string) string {
	if len(hex) == 7 {
		return "rgb(" + hex[1:] + ")"
	}
	return "rgb(ffffff)"
}
func hyprRGBA(hex, alpha string) string {
	if len(hex) == 7 {
		return fmt.Sprintf("rgba(%s%s)", hex[1:], alpha)
	}
	return "rgba(ffffff" + alpha + ")"
}
