package theme

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/prettyletto/omagen/backend/internal/fsutil"
)

// WriteShell composes shell surfaces and bar overrides into the one shell.toml
// file Quattro loads for a theme.
func WriteShell(themeDir string, palette Palette, surface, detail, barSurface, barDensity, barAttention, barForm string) error {
	if !validChoice(surface, "native", "flat", "layered", "contrast", "accent") {
		return fmt.Errorf("invalid shell surface %q", surface)
	}
	if !validChoice(detail, "native", "framed", "edge", "focus") {
		return fmt.Errorf("invalid shell detail %q", detail)
	}
	if !validChoice(barSurface, "native", "dark", "light", "accent") ||
		!validChoice(barDensity, "native", "compact", "comfortable") ||
		!validChoice(barAttention, "semantic", "accent") ||
		!validChoice(barForm, "continuous", "docked") {
		return fmt.Errorf("invalid bar style")
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by Omagen. Shell: surface=%s detail=%s. Bar: surface=%s density=%s attention=%s form=%s.\n", surface, detail, barSurface, barDensity, barAttention, barForm)
	b.WriteString("# Native values are omitted so Quattro remains authoritative.\n\n")

	// Surface composition distributes the generated neutral ramp across the
	// shell's existing surfaces; it does not change transparency or layout.
	popup, control, selected := palette.Background, palette.LighterBackground, palette.Selection
	controlsSection := false
	switch surface {
	case "layered":
		popup, control = palette.DarkBackground, palette.LighterBackground
	case "contrast":
		popup, control, selected = palette.LighterBackground, palette.LighterBackground, palette.Accent
	case "accent":
		// Accent is a state treatment, not a full-bleed surface.  The shell
		// keeps its neutral card background while using the generated accent for
		// selected rows and focus chrome below.
		popup, control, selected = palette.DarkBackground, palette.LighterBackground, palette.Accent
	}
	if surface != "flat" {
		fmt.Fprintf(&b, "[popups]\nbackground = %q\n\n", popup)
		fmt.Fprintf(&b, "[menu]\nbackground = %q\nselected-background = %q\n", popup, selected)
		if surface == "accent" {
			fmt.Fprintf(&b, "selected-background-alpha = 0.18\nselected-text = %q\n", palette.Accent)
		}
		if detail == "edge" {
			b.WriteString("selected-border-width = \"0 0 0 3\"\n")
		}
		if detail == "focus" {
			b.WriteString("selected-border-width = 1\n")
		}
		b.WriteString("\n")
		fmt.Fprintf(&b, "[launcher]\nbackground = %q\nselected-background = %q\n", popup, selected)
		if surface == "accent" {
			fmt.Fprintf(&b, "selected-background-alpha = 0.18\nselected-text = %q\n", palette.Accent)
		}
		b.WriteString("\n")
		fmt.Fprintf(&b, "[controls]\nnormal-color = %q\nnormal-fill-alpha = 1.0\nselected-color = %q\n", control, selected)
		if surface == "accent" {
			fmt.Fprintf(&b, "selected-fill-alpha = 0.18\nselected-border = %q\nselected-border-alpha = 0.78\n", palette.Accent)
		} else {
			b.WriteString("selected-fill-alpha = 1.0\n")
		}
		controlsSection = true
	}

	// Detail changes border language only; Quattro's existing colors and
	// interaction states remain intact.
	switch detail {
	case "framed":
		if !controlsSection {
			b.WriteString("[controls]\n")
			controlsSection = true
		}
		b.WriteString("normal-border-width = 1\nhover-cursor-border-width = 1\nfocus-border-width = 1\nselected-border-width = 1\n\n")
		b.WriteString("[popups]\nborder-width = 1\n\n")
		if surface == "flat" {
			b.WriteString("[menu]\nborder-width = 1\n\n")
		}
		if surface == "flat" {
			b.WriteString("[notifications]\nborder-width = 1\n")
		}
	case "edge":
		if !controlsSection {
			b.WriteString("[controls]\n")
			controlsSection = true
		}
		b.WriteString("normal-border-width = 0\nselected-border-width = \"0 0 0 3\"\n")
		if surface == "flat" {
			b.WriteString("\n[menu]\nselected-border-width = \"0 0 0 3\"\n\n[notifications]\nborder-width = \"0 0 0 3\"\n")
		}
	case "focus":
		if !controlsSection {
			b.WriteString("[controls]\n")
			controlsSection = true
		}
		b.WriteString("normal-border-width = 0\nhover-cursor-border-width = 0\nfocus-border-width = 1\nselected-border-width = 1\n")
		if surface == "native" {
			b.WriteString("\n[menu]\nselected-border-width = 1\n\n[notifications]\nborder-width = 0\n")
		}
	}

	if err := appendBarOverrides(&b, palette, barSurface, barDensity, barAttention, barForm); err != nil {
		return err
	}

	return fsutil.AtomicWriteFile(filepath.Join(themeDir, "shell.toml"), []byte(b.String()), 0o644)
}

func validChoice(value string, choices ...string) bool {
	for _, choice := range choices {
		if value == choice {
			return true
		}
	}
	return false
}
