package theme

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/prettyletto/omagen/backend/internal/fsutil"
)

var generatedShellFiles = []string{
	"shell.toml",
	"shell.bar.toml",
	"shell.popups.toml",
	"shell.menu.toml",
	"shell.launcher.toml",
	"shell.controls.toml",
	"shell.notifications.toml",
}

var generatedOmagenFiles = []string{"omagen.bar.toml"}

type shellSection struct {
	name string
	body strings.Builder
}

// WriteShell emits Quattro's section-level shell overrides. The generated
// root shell.toml is intentionally left to Quattro's default template.
func WriteShell(themeDir string, palette Palette, surface, detail, barSurface, barDensity, barAttention, barForm string) error {
	if !validChoice(surface, "native", "flat", "layered", "contrast", "accent") {
		return fmt.Errorf("invalid shell surface %q", surface)
	}
	if !validChoice(detail, "native", "framed", "edge", "focus") {
		return fmt.Errorf("invalid shell detail %q", detail)
	}
	if !validChoice(barSurface, "native", "dark", "light", "accent") ||
		!validChoice(barDensity, "native", "compact", "comfortable") ||
		!validChoice(barAttention, "semantic", "accent") ||
		!validChoice(barForm, "continuous", "docked") {
		return fmt.Errorf("invalid bar style")
	}

	if err := clearGeneratedThemeFiles(themeDir); err != nil {
		return err
	}

	popups := shellSection{name: "popups"}
	menu := shellSection{name: "menu"}
	launcher := shellSection{name: "launcher"}
	controls := shellSection{name: "controls"}
	notifications := shellSection{name: "notifications"}
	bar := shellSection{name: "bar"}

	// Surface composition distributes the generated neutral ramp across the
	// shell's existing surfaces; it does not change transparency or layout.
	popup, control, selected := palette.Background, palette.LighterBackground, palette.Selection
	switch surface {
	case "layered":
		popup, control = palette.DarkBackground, palette.LighterBackground
	case "contrast":
		popup, control, selected = palette.LighterBackground, palette.LighterBackground, palette.Accent
	case "accent":
		// Accent is a state treatment, not a full-bleed surface. The shell
		// keeps its neutral card background while using the generated accent for
		// selected rows and focus chrome below.
		popup, control, selected = palette.DarkBackground, palette.LighterBackground, palette.Accent
	}
	if surface != "flat" {
		fmt.Fprintf(&popups.body, "background = %q\n", popup)
		fmt.Fprintf(&menu.body, "background = %q\nselected-background = %q\n", popup, selected)
		if surface == "accent" {
			fmt.Fprintf(&menu.body, "selected-background-alpha = 0.18\nselected-text = %q\n", palette.Accent)
		}
		if detail == "edge" {
			menu.body.WriteString("selected-border-width = \"0 0 0 3\"\n")
		}
		if detail == "focus" {
			menu.body.WriteString("selected-border-width = 1\n")
		}
		fmt.Fprintf(&launcher.body, "background = %q\nselected-background = %q\n", popup, selected)
		if surface == "accent" {
			fmt.Fprintf(&launcher.body, "selected-background-alpha = 0.18\nselected-text = %q\n", palette.Accent)
		}
		fmt.Fprintf(&controls.body, "normal-color = %q\nnormal-fill-alpha = 1.0\nselected-color = %q\n", control, selected)
		if surface == "accent" {
			fmt.Fprintf(&controls.body, "selected-fill-alpha = 0.18\nselected-border = %q\nselected-border-alpha = 0.78\n", palette.Accent)
		} else {
			controls.body.WriteString("selected-fill-alpha = 1.0\n")
		}
	}

	// Detail changes border language only; Quattro's existing colors and
	// interaction states remain intact.
	switch detail {
	case "framed":
		controls.body.WriteString("normal-border-width = 1\nhover-cursor-border-width = 1\nfocus-border-width = 1\nselected-border-width = 1\n")
		popups.body.WriteString("border-width = 1\n")
		if surface == "flat" {
			menu.body.WriteString("border-width = 1\n")
			notifications.body.WriteString("border-width = 1\n")
		}
	case "edge":
		controls.body.WriteString("normal-border-width = 0\nselected-border-width = \"0 0 0 3\"\n")
		if surface == "flat" {
			menu.body.WriteString("selected-border-width = \"0 0 0 3\"\n")
			notifications.body.WriteString("border-width = \"0 0 0 3\"\n")
		}
	case "focus":
		controls.body.WriteString("normal-border-width = 0\nhover-cursor-border-width = 0\nfocus-border-width = 1\nselected-border-width = 1\n")
		if surface == "native" {
			notifications.body.WriteString("border-width = 0\n")
		}
	}

	if err := appendBarOverrides(&bar.body, palette, barSurface, barDensity, barAttention, barForm); err != nil {
		return err
	}
	if barForm == "docked" {
		const metadata = "# Generated by Omagen.\nform = \"docked\"\n"
		if err := fsutil.AtomicWriteFile(filepath.Join(themeDir, "omagen.bar.toml"), []byte(metadata), 0o644); err != nil {
			return fmt.Errorf("write omagen.bar.toml: %w", err)
		}
	}

	for _, section := range []*shellSection{&bar, &popups, &menu, &launcher, &controls, &notifications} {
		if strings.TrimSpace(section.body.String()) == "" {
			continue
		}
		content := "# Generated by Omagen.\n" + section.body.String()
		path := filepath.Join(themeDir, "shell."+section.name+".toml")
		if err := fsutil.AtomicWriteFile(path, []byte(content), 0o644); err != nil {
			return fmt.Errorf("write shell.%s.toml: %w", section.name, err)
		}
	}
	return nil
}

func clearGeneratedThemeFiles(themeDir string) error {
	for _, name := range append(generatedShellFiles, generatedOmagenFiles...) {
		if err := fsutil.RemoveFileAndSync(filepath.Join(themeDir, name)); err != nil {
			return fmt.Errorf("remove old %s: %w", name, err)
		}
	}
	return nil
}

func validChoice(value string, choices ...string) bool {
	for _, choice := range choices {
		if value == choice {
			return true
		}
	}
	return false
}
